{{- if .Values.bgpAdvertisement.enabled -}}
apiVersion: metallb.io/v1beta1
kind: BGPAdvertisement
metadata:
  name: {{ .Values.bgpAdvertisement.name }}
  namespace: {{ .Values.bgpAdvertisement.namespace | default .Values.namespace }}
spec:
  ipAddressPools:
  {{- with .Values.bgpAdvertisement.ipAddressPools }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
