{{ if .Values.ipAddressPool.enabled -}}
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: {{ .Values.ipAddressPool.name }}
  namespace: {{ .Values.bgpAdvertisement.namespace | default .Values.namespace }}
spec:
  addresses:
  {{- with .Values.ipAddressPool.addresses }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
